gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - '#d79921'
      - bold
    inactiveBorderColor:
      - '#a89984'
    selectedLineBgColor:
      - '#3c3836'

git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --side-by-side --line-numbers
